DECLARE SUB setScreen CDECL(BYVAL bum AS BYTE)
DECLARE SUB clearScreen CDECL()
DECLARE SUB drawLineHorzByLen CDECL(BYVAL x AS INTEGER, BYVAL y AS INTEGER, BYVAL l AS INTEGER, BYVAL C AS INTEGER)
DECLARE SUB drawLineVertByLen CDECL(BYVAL x AS INTEGER, BYVAL y AS INTEGER, BYVAL l AS INTEGER, BYVAL C AS INTEGER)
DECLARE FUNCTION getTimer CDECL() AS INTEGER
